import type { SceneDef } from "./types.js";

export const TITLE_VI = "Nghịch lý Murphy: Vì sao mọi thứ luôn hỏng đúng lúc?";
export const TITLE_EN = "Murphy's Law: Why Things Always Go Wrong at the Worst Time";

export const SCENES: SceneDef[] = [
  {
    id: "scene-01",
    title: "Hook",
    targetDuration: 24,
    music: "curious",
    captions: [
      { vi: "Bảy giờ sáng. Bạn đang vội đi làm.", en: "Seven a.m. You're rushing off to work." },
      { vi: "Nhưng lần này, bạn đã chuẩn bị mọi thứ từ tối hôm trước.", en: "But this time, you got everything ready the night before." },
      { vi: "Quần áo đã là phẳng. Điện thoại đầy pin. Báo thức đã đặt.", en: "Clothes ironed. Phone fully charged. Alarm set." },
      { vi: "Bạn tự tin bước ra khỏi nhà...", en: "You step out the door, full of confidence..." },
      { vi: "Và đúng lúc đó, trời bắt đầu mưa. Xe thì không chịu nổ máy.", en: "And right then, it starts to rain. Your scooter refuses to start." },
      { vi: "Còn chìa khóa nhà... vừa biến mất.", en: "And your house keys... have just vanished." },
      { vi: "Bạn có bao giờ cảm thấy cuộc đời dường như cố tình chống lại kế hoạch của mình không?", en: "Have you ever felt like life is deliberately working against your plans?" },
      { vi: "Nếu có, bạn không cô đơn. Cảm giác này có hẳn một cái tên: Nghịch lý Murphy.", en: "If so, you're not alone. This feeling even has a name: Murphy's Law." },
    ],
    visual_summary:
      "Buổi sáng tự tin trong căn hộ (đồng hồ, checklist) → bước ra ngoài, mưa đổ, xe không nổ, mặt sốc.",
    shots: [
      {
        id: "s01a-morning",
        fromCaption: 0,
        prompt: {
          scene: "the character confidently buttoning his shirt next to a neatly packed backpack, phone on a charger showing full battery, wall clock near 7 o'clock, smug satisfied smile",
          environment: "small cozy modern Vietnamese apartment, window with morning city view, a few plants",
          composition: "cinematic wide shot, character slightly left of center, empty space on the right",
          lighting: "soft golden morning light through the window",
          mood: "optimistic, organized, quietly proud",
          camera: "eye level, 35mm lens feel",
        },
      },
      {
        id: "s01b-rain-scooter",
        fromCaption: 4,
        prompt: {
          scene: "the character standing next to his scooter outside an apartment building, the scooter will not start, rain starting to fall, he pats his empty pockets looking for missing keys, exaggerated shocked expression, comedic body language",
          environment: "narrow urban Vietnamese street, apartment entrance, wet pavement, grey clouds",
          composition: "cinematic wide composition, character center-left, scooter beside him, sky area at the top",
          lighting: "cool overcast light with soft reflections on wet ground",
          mood: "comedic disaster, sudden bad luck",
          camera: "slightly low angle, wide lens",
        },
      },
    ],
    animation:
      "Camera đẩy chậm vào nhân vật (100%→108%, easeInOutCubic); đồng hồ vector chạy kim; checklist tick lần lượt; cắt sang shot mưa: hạt mưa xuất hiện, rung camera khi xe không nổ, dấu '!' bật easeOutBack; kết thúc tiêu đề 'Murphy's Law' hiện lên.",
    sfx: [
      { id: "tick", caption: 0, offset: 0.0 },
      { id: "ding", caption: 2, offset: 0.4 },
      { id: "ding", caption: 2, offset: 1.5 },
      { id: "ding", caption: 2, offset: 2.6 },
      { id: "whoosh", caption: 4, offset: -0.3 },
      { id: "rain", caption: 4, offset: 0 },
      { id: "crank", caption: 4, offset: 2.2 },
      { id: "scratch", caption: 5, offset: 0.9 },
      { id: "swell", caption: 7, offset: 2.0 },
    ],
  },
  {
    id: "scene-02",
    title: "Murphy's Law là gì?",
    targetDuration: 36,
    music: "curious",
    captions: [
      { vi: "Nghịch lý Murphy thường được tóm gọn trong một câu:", en: "Murphy's Law is usually summed up in a single sentence:" },
      { vi: "“Điều gì có thể xảy ra sai, thì nó sẽ xảy ra sai.”", en: "“Anything that can go wrong, will go wrong.”" },
      { vi: "Cái tên được cho là đến từ Edward Murphy, một kỹ sư hàng không Mỹ cuối thập niên 1940.", en: "The name is said to come from Edward Murphy, an American aerospace engineer in the late 1940s." },
      { vi: "Nghe như định luật vật lý, nhưng thật ra không phải.", en: "It sounds like a law of physics, but it really isn't." },
      { vi: "Không có phương trình nào chứng minh vũ trụ ghét bạn.", en: "No equation proves that the universe hates you." },
      { vi: "Nó là một cách nói hài hước về rủi ro, xác suất và sự chuẩn bị.", en: "It's a humorous way of talking about risk, probability, and preparation." },
      { vi: "Và về một thói quen rất con người: ta nhớ rất rõ những lần mọi thứ đi sai.", en: "And about a very human habit: we remember the times things went wrong extremely well." },
    ],
    visual_summary: "Nhân vật đứng giữa không gian tối giản, nhìn trái phải; câu trích dẫn hiện lên; icon thất bại xuất hiện lần lượt.",
    shots: [
      {
        id: "s02-thinking",
        fromCaption: 0,
        prompt: {
          scene: "the character standing with one hand on his chin, raising an eyebrow, glancing sideways with a skeptical, curious look",
          environment: "minimal abstract background of soft teal and warm paper tones with subtle geometric shapes",
          composition: "medium-wide shot, character in the lower right third, large clean negative space on the left and top for overlays",
          lighting: "soft studio key light with gentle rim light",
          mood: "curious, witty, slightly skeptical",
          camera: "eye level, gentle depth of field",
        },
      },
    ],
    animation:
      "Câu 'Anything that can go wrong...' gõ từng chữ ở vùng trống bên trái; icon thất bại (pin cạn, mưa, đèn đỏ, bug, chìa khóa) pop-in tuần tự easeOutBack; nhân vật 'nhìn trái/phải' bằng pan ngang nhẹ; dấu gạch chéo lên 'định luật vật lý'.",
    sfx: [
      { id: "whoosh", caption: 0, offset: -0.4 },
      { id: "typing", caption: 1, offset: 0 },
      { id: "pop", caption: 5, offset: 0.2 },
      { id: "pop", caption: 5, offset: 0.9 },
      { id: "pop", caption: 5, offset: 1.6 },
      { id: "pop", caption: 6, offset: 0.4 },
      { id: "pop", caption: 6, offset: 1.1 },
      { id: "error", caption: 3, offset: 2.2, gainDb: -6 },
    ],
  },
  {
    id: "scene-03",
    title: "Bánh mì phết bơ",
    targetDuration: 36,
    music: "curious",
    captions: [
      { vi: "Bắt đầu với một ví dụ kinh điển: lát bánh mì phết bơ.", en: "Let's start with a classic: a slice of buttered toast." },
      { vi: "Bạn lỡ tay làm rơi nó. Và gần như chắc chắn, mặt có bơ sẽ úp xuống sàn.", en: "You drop it by accident. And almost inevitably, it lands butter-side down." },
      { vi: "Vũ trụ đang trêu bạn chăng? Không hẳn.", en: "Is the universe teasing you? Not exactly." },
      { vi: "Bánh thường rơi từ độ cao mặt bàn, và bắt đầu xoay khi trượt khỏi mép.", en: "Toast usually falls from table height, and starts spinning as soon as it slips off the edge." },
      { vi: "Với độ cao đó, nó thường chỉ kịp xoay khoảng nửa vòng trước khi chạm đất.", en: "From that height, it usually only manages about half a turn before it hits the floor." },
      { vi: "Thêm nữa, lần úp bơ để lại vết bẩn đáng nhớ, còn lần may mắn thì ta quên ngay.", en: "Plus, a butter-down landing leaves a memorable mess, while the lucky landings are forgotten instantly." },
    ],
    visual_summary: "Bếp nhỏ buổi sáng; lát bánh vector rơi, xoay nửa vòng, úp bơ xuống, nảy nhẹ; sơ đồ quỹ đạo + nhãn độ cao.",
    shots: [
      {
        id: "s03-kitchen",
        fromCaption: 0,
        prompt: {
          scene: "the character in a small kitchen staring down at the floor in disbelief, one hand frozen mid-air as if he just dropped something, mouth open, empty plate on the counter",
          environment: "compact bright Vietnamese apartment kitchen, wooden counter at waist height, tiled floor clearly visible in the lower part of the frame",
          composition: "wide shot, character on the left third, counter edge and an open stretch of floor on the right half kept clear",
          lighting: "warm morning light from a side window",
          mood: "comic disbelief",
          camera: "eye level, slightly wide",
        },
      },
    ],
    animation:
      "Lát bánh (vẽ bằng canvas) trượt khỏi mép bàn, xoay ~180° theo trọng lực, camera theo bánh xuống (tilt), va chạm có bounce + squash, vệt bơ; đường quỹ đạo nét đứt + nhãn '~75 cm' và '½ vòng'; icon não 'nhớ'/'quên'.",
    sfx: [
      { id: "whoosh", caption: 1, offset: 0.5 },
      { id: "thud", caption: 1, offset: 1.4 },
      { id: "scratch", caption: 2, offset: 0.1 },
      { id: "pop", caption: 3, offset: 0.6 },
      { id: "pop", caption: 4, offset: 0.6 },
      { id: "thud", caption: 4, offset: 2.4, gainDb: -6 },
    ],
  },
  {
    id: "scene-04",
    title: "USB",
    targetDuration: 34,
    music: "curious",
    captions: [
      { vi: "Còn đây là bài kiểm tra tâm lý của thời đại công nghệ: cắm USB.", en: "And here's the psychological test of the tech age: plugging in a USB." },
      { vi: "Một chiếc USB chỉ có hai mặt. Xác suất cắm đúng là năm mươi phần trăm.", en: "A USB plug has only two sides. Your odds of getting it right: fifty percent." },
      { vi: "Bạn cắm lần đầu. Sai.", en: "First try. Wrong." },
      { vi: "Bạn xoay lại. Vẫn sai.", en: "You flip it. Still wrong." },
      { vi: "Bạn xoay thêm lần nữa... và nó vào. Đúng hướng ban đầu.", en: "You flip it once more... and it slides in. The original way." },
      { vi: "Toán học nói năm mươi phần trăm. Kinh nghiệm thì nói: không bao giờ là lần đầu.", en: "Math says fifty percent. Experience says: never on the first try." },
    ],
    visual_summary: "Bàn làm việc, nhân vật cầm USB bực bội; cận cảnh vector: USB tiến vào cổng, bật ra, xoay 180°, bật ra, khựng lại, xoay, vào.",
    shots: [
      {
        id: "s04-desk-usb",
        fromCaption: 0,
        prompt: {
          scene: "the character sitting at a desk, leaning toward the side of a laptop, squinting with intense concentration while holding a small USB stick, comically frustrated eyebrows",
          environment: "tidy home office desk, laptop, desk lamp, small plant, calm wall",
          composition: "medium shot, character on the right half, the left half of the frame is a clean calm wall area",
          lighting: "warm desk lamp light mixed with cool daylight",
          mood: "focused frustration, everyday comedy",
          camera: "eye level, medium focal length",
        },
      },
    ],
    animation:
      "Panel cận cảnh bên trái: cổng USB + đầu USB vector. Lần 1 tiến vào → bật lại (shake, dấu X đỏ); xoay 180° (easeInOutCubic) → lần 2 bật lại; khựng 'dramatic pause' (zoom nhẹ, nhạc nín); xoay lại → cắm vào (easeOutBack, dấu ✓ xanh). Đồng hồ 50% hiện ở caption 2.",
    sfx: [
      { id: "whoosh", caption: 0, offset: -0.3 },
      { id: "error", caption: 2, offset: 0.9 },
      { id: "whoosh", caption: 3, offset: 0.1, gainDb: -6 },
      { id: "error", caption: 3, offset: 1.0 },
      { id: "whoosh", caption: 4, offset: 0.2, gainDb: -6 },
      { id: "success", caption: 4, offset: 2.0 },
      { id: "ding", caption: 5, offset: 0.2 },
    ],
  },
  {
    id: "scene-05",
    title: "Khi viết code",
    targetDuration: 48,
    music: "curious",
    captions: [
      { vi: "Nếu bạn là lập trình viên, hẳn bạn thuộc câu thần chú: “Ở máy em thì chạy mà.”", en: "If you're a developer, you know the magic words by heart: “It works on my machine.”" },
      { vi: "Ở local, mọi thứ hoàn hảo. Build xanh, test qua hết.", en: "Locally, everything is perfect. Build green, all tests passing." },
      { vi: "Rồi bạn deploy lên production. Và mọi thứ sụp đổ.", en: "Then you deploy to production. And everything falls apart." },
      { vi: "Thiếu một biến môi trường. API bị timeout.", en: "A missing environment variable. An API timeout." },
      { vi: "Một package lệch phiên bản. Database từ chối kết nối.", en: "A package on a different version. The database refuses to connect." },
      { vi: "Nhưng Murphy không nói rằng code của bạn chắc chắn sẽ lỗi.", en: "But Murphy isn't saying your code is guaranteed to fail." },
      { vi: "Ông ấy nhắc rằng: nếu một kiểu lỗi có thể xảy ra mà bạn không chuẩn bị,", en: "He's reminding you: if a failure mode can happen and you haven't prepared for it," },
      { vi: "thì một ngày nào đó, nó sẽ xảy ra, đúng vào lúc bạn không muốn nhất.", en: "one day it will happen, at exactly the moment you least want it to." },
    ],
    visual_summary: "Nhân vật tự tin trước laptop, terminal xanh 'works locally'; chuyển sang production: đèn đỏ, lỗi bật ra, icon .env biến mất, mặt sốc.",
    shots: [
      {
        id: "s05a-dev-confident",
        fromCaption: 0,
        prompt: {
          scene: "the character sitting at a laptop leaning back in his chair with arms crossed and a confident smug grin, coffee mug beside him",
          environment: "modern cozy workspace, soft green and teal accents, monitor glow, bookshelf softly blurred",
          composition: "medium-wide shot, character on the right third, left half of the frame kept as a calm dark wall for UI overlays",
          lighting: "soft cool screen glow plus warm ambient lamp",
          mood: "confident, everything under control",
          camera: "eye level, slight three-quarter angle",
        },
      },
      {
        id: "s05b-dev-shocked",
        fromCaption: 2,
        prompt: {
          scene: "the same character at the same laptop, now leaning forward in panic, hands on his head, eyes wide, mouth open, cold sweat drop",
          environment: "same workspace at night, red alert glow reflecting from the screen onto his face and the wall",
          composition: "medium-wide shot, character on the right third, left half of the frame kept as dark wall space for UI overlays",
          lighting: "dramatic red and cool blue glow from the screen, dark room",
          mood: "production incident panic, comedic",
          camera: "eye level, slight dutch tilt",
        },
      },
    ],
    animation:
      "Terminal UI gõ lệnh 'npm install', 'npm run build', 'npm test' với dòng xanh ✓ 'works locally'; chuyển cảnh glitch sang production; các thẻ lỗi đỏ pop-in (ENV missing, API timeout, version mismatch, DB connection failed) kèm rung; icon '.env' mờ dần biến mất; nhân vật từ tự tin sang hoảng (đổi shot + flash đỏ); cuối scene trích dẫn Murphy nổi lên.",
    sfx: [
      { id: "typing", caption: 1, offset: 0 },
      { id: "success", caption: 1, offset: 3.0 },
      { id: "whoosh", caption: 2, offset: 0.6 },
      { id: "error", caption: 3, offset: 0.1 },
      { id: "error", caption: 3, offset: 1.6 },
      { id: "error", caption: 4, offset: 0.1 },
      { id: "error", caption: 4, offset: 1.8 },
      { id: "swell", caption: 6, offset: 0 },
    ],
  },
  {
    id: "scene-06",
    title: "Trong đời sống",
    targetDuration: 38,
    music: "curious",
    captions: [
      { vi: "Và Murphy không chỉ sống trong máy tính. Ông ấy ở khắp nơi.", en: "And Murphy doesn't just live inside computers. He's everywhere." },
      { vi: "Đang muộn giờ? Đèn đỏ nào cũng đứng chờ sẵn bạn.", en: "Running late? Every single traffic light is waiting for you, red." },
      { vi: "Cần Internet gấp? Wi-Fi chọn đúng lúc đó để mất sóng.", en: "Need the internet urgently? That's exactly when the Wi-Fi drops out." },
      { vi: "Mang ô theo, trời nắng đẹp cả ngày.", en: "Bring an umbrella, and it's sunny all day." },
      { vi: "Quên ô ở nhà, trời đổ mưa như trút.", en: "Leave it at home, and it pours." },
      { vi: "Và khi cần gọi một cuộc điện thoại quan trọng... pin còn đúng một phần trăm.", en: "And when you need to make an important call... your battery is at exactly one percent." },
    ],
    visual_summary: "Montage nhanh: kẹt đèn đỏ trên xe máy; Wi-Fi biến mất; ô + nắng / không ô + mưa; điện thoại 1%.",
    shots: [
      {
        id: "s06a-traffic",
        fromCaption: 0,
        prompt: {
          scene: "the character on his scooter wearing a helmet, stopped at a red light, checking his wristwatch with an exasperated look, other scooters around him",
          environment: "busy Vietnamese city intersection in the morning, shop fronts, power lines",
          composition: "cinematic wide composition, character center-right, upper left area kept relatively open",
          lighting: "bright hazy morning sunlight",
          mood: "impatient, comedic frustration",
          camera: "eye level, wide lens",
        },
      },
      {
        id: "s06b-umbrella-sun",
        fromCaption: 3,
        prompt: {
          scene: "the character walking on a sunny sidewalk holding a closed umbrella, sweating slightly, looking up at a perfectly clear sky with an annoyed deadpan face",
          environment: "sunny Vietnamese street with trees and shophouses",
          composition: "wide shot, character center, lots of bright sky at the top",
          lighting: "strong bright midday sunlight, crisp soft shadows",
          mood: "ironic, deadpan humor",
          camera: "slightly low angle",
        },
      },
      {
        id: "s06c-phone-battery",
        fromCaption: 5,
        prompt: {
          scene: "the character holding his smartphone close to his face, staring at it in horror, the phone screen glowing red, sweat drop",
          environment: "simple blurred street background at dusk",
          composition: "medium close-up, character on the right half, left half of the frame calm and blurred",
          lighting: "dusk ambient light with red glow from the phone on his face",
          mood: "panic, comedic tension",
          camera: "eye level, shallow depth of field",
        },
      },
    ],
    animation:
      "Montage nhịp nhanh với wipe chuyển cảnh: đèn giao thông vector chuyển xanh→vàng→đỏ; icon Wi-Fi rút từng vạch rồi biến mất kèm dấu '!'; nắng: tia nắng xoay; cắt mưa: overlay mưa + tối trời; pin tụt 100%→1% nhấp nháy đỏ.",
    sfx: [
      { id: "whoosh", caption: 1, offset: -0.2 },
      { id: "click", caption: 1, offset: 1.2 },
      { id: "whoosh", caption: 2, offset: -0.2 },
      { id: "error", caption: 2, offset: 1.6 },
      { id: "whoosh", caption: 3, offset: -0.2 },
      { id: "rain", caption: 4, offset: 0.2 },
      { id: "whoosh", caption: 5, offset: -0.2 },
      { id: "error", caption: 5, offset: 2.6 },
    ],
  },
  {
    id: "scene-07",
    title: "Vì sao ta thấy Murphy đúng?",
    targetDuration: 48,
    music: "curious",
    captions: [
      { vi: "Vậy tại sao chúng ta lại thấy Murphy đúng đến vậy?", en: "So why does Murphy's Law feel so true?" },
      { vi: "Thứ nhất, não ghi nhớ chuyện xấu đậm hơn chuyện tốt.", en: "First, the brain records bad events more vividly than good ones." },
      { vi: "Một lần lỡ chuyến bay nhớ cả chục năm, còn trăm chuyến đúng giờ chẳng ai kể lại.", en: "One missed flight can stay with you for a decade, but a hundred on-time flights never get mentioned." },
      { vi: "Các nhà tâm lý học gọi đó là thiên kiến tiêu cực.", en: "Psychologists call this negativity bias." },
      { vi: "Thứ hai, khi đã tin mình xui, ta chỉ để ý bằng chứng cho thấy mình xui.", en: "Second, once we believe we're unlucky, we only notice the evidence that proves it." },
      { vi: "Đó là thiên kiến xác nhận.", en: "That's confirmation bias." },
      { vi: "Và thứ ba, chuyện gì càng dễ nhớ lại, ta càng nghĩ nó xảy ra thường xuyên.", en: "And third, the easier something is to recall, the more often we think it happens." },
      { vi: "Ngày bình yên lặng lẽ trôi qua. Chỉ ngày xui xẻo là ở lại.", en: "The peaceful days slip quietly by. Only the unlucky ones stay with us." },
    ],
    visual_summary: "Nhân vật ngồi trầm tư; bong bóng ký ức nổi lên: chuyện xui phình to, rực màu; chuyện suôn sẻ nhỏ lại, mờ dần.",
    shots: [
      {
        id: "s07-memory",
        fromCaption: 0,
        prompt: {
          scene: "the character sitting on a park bench, looking up thoughtfully at the empty sky above him, chin resting on his hand, calm reflective expression",
          environment: "quiet city park at late afternoon, soft trees, open sky",
          composition: "wide shot, character small in the lower center, the entire upper two thirds of the frame is open soft sky for overlays",
          lighting: "soft warm late-afternoon light",
          mood: "reflective, gentle, curious",
          camera: "eye level, wide lens, deep negative space",
        },
      },
    ],
    animation:
      "Bong bóng ký ức nổi lên từ đầu nhân vật (bob nhẹ); bong bóng xui (mưa, đèn đỏ, USB, bug) phình to + màu đậm; bong bóng 'bình thường' (✓ đúng giờ, ☀) thu nhỏ, mờ, trôi về nền; nhãn 3 thiên kiến xuất hiện theo câu thoại.",
    sfx: [
      { id: "bubble", caption: 1, offset: 0.3 },
      { id: "bubble", caption: 2, offset: 0.2 },
      { id: "bubble", caption: 2, offset: 1.2 },
      { id: "ding", caption: 3, offset: 0.3 },
      { id: "ding", caption: 5, offset: 0.1 },
      { id: "bubble", caption: 6, offset: 0.3 },
      { id: "ding", caption: 6, offset: 0.2, gainDb: -6 },
    ],
  },
  {
    id: "scene-08",
    title: "Murphy có vô nghĩa?",
    targetDuration: 38,
    music: "warm",
    captions: [
      { vi: "Vậy Nghịch lý Murphy có vô nghĩa không? Hoàn toàn không.", en: "So is Murphy's Law meaningless? Not at all." },
      { vi: "Nếu xem nó như một nguyên tắc quản lý rủi ro, nó cực kỳ hữu ích.", en: "Treated as a risk-management principle, it's extremely useful." },
      { vi: "Bạn sao lưu dữ liệu, vì ổ cứng có thể hỏng.", en: "You back up your data, because hard drives can fail." },
      { vi: "Bạn chạy test trước khi deploy, vì code có thể lỗi.", en: "You run tests before deploying, because code can break." },
      { vi: "Bạn mang sạc dự phòng, đến sân bay sớm, và luôn có một phương án B.", en: "You carry a power bank, get to the airport early, and always keep a Plan B." },
      { vi: "Kỹ sư, phi công hay bác sĩ đều làm việc với cách nghĩ này.", en: "Engineers, pilots, and doctors all work with this mindset." },
    ],
    visual_summary: "Hỗn loạn biến thành checklist: icon backup, test, ô, sạc dự phòng, thẻ Plan B lần lượt được tick.",
    shots: [
      {
        id: "s08-prepared",
        fromCaption: 0,
        prompt: {
          scene: "the character calmly packing a backpack on a table: a power bank, a folded umbrella, a small external hard drive, a laptop, with a relaxed confident smile",
          environment: "bright tidy apartment by a window, morning",
          composition: "medium-wide shot, character and table on the right half, left half of the frame is a clean light wall for a checklist overlay",
          lighting: "fresh soft morning daylight",
          mood: "calm, prepared, quietly confident",
          camera: "eye level, gentle three-quarter angle",
        },
      },
    ],
    animation:
      "Icon lỗi hỗn loạn xoay tròn rồi 'hút' vào panel checklist; 5 dòng checklist (Backup, Test, Ô, Sạc dự phòng, Plan B) trượt vào + tick xanh easeOutBack theo câu thoại; thẻ Plan B lật ra.",
    sfx: [
      { id: "swell", caption: 0, offset: 1.5 },
      { id: "whoosh", caption: 1, offset: 0.4 },
      { id: "success", caption: 2, offset: 0.5 },
      { id: "success", caption: 3, offset: 0.5 },
      { id: "click", caption: 4, offset: 0.4 },
      { id: "click", caption: 4, offset: 1.6 },
      { id: "success", caption: 4, offset: 3.2 },
    ],
  },
  {
    id: "scene-09",
    title: "Kết luận",
    targetDuration: 28,
    music: "warm",
    captions: [
      { vi: "Vậy nên, Nghịch lý Murphy không có nghĩa là cuộc đời luôn chống lại bạn.", en: "So Murphy's Law doesn't mean life is always against you." },
      { vi: "Nó có nghĩa là: nếu một điều có thể đi sai, hãy chuẩn bị cho nó.", en: "It means: if something can go wrong, prepare for it." },
      { vi: "Bình tĩnh, có kế hoạch, và có cả phương án dự phòng.", en: "Stay calm, make a plan, and keep a backup plan too." },
      { vi: "Và nếu bạn nghĩ video này không thể lỗi...", en: "And if you think this video can't possibly go wrong..." },
      { vi: "...hãy nhớ đến Murphy.", en: "...remember Murphy." },
    ],
    visual_summary: "Nhân vật mỉm cười trên ban công hoàng hôn với tách cà phê; câu kết hiện ra; glitch hài cuối rồi fade đen.",
    shots: [
      {
        id: "s09-calm",
        fromCaption: 0,
        prompt: {
          scene: "the character standing on a small balcony holding a cup of coffee, relaxed genuine smile, looking at the viewer",
          environment: "Vietnamese city rooftops at golden hour, potted plants on the balcony",
          composition: "medium-wide shot, character on the right third, open sky on the left for a quote",
          lighting: "warm golden-hour sunset light, soft long shadows",
          mood: "calm, warm, reassuring",
          camera: "eye level, gentle depth",
        },
      },
    ],
    animation:
      "Camera kéo ra chậm, bụi nắng lơ lửng; câu kết 'If it can go wrong, prepare for it' hiện chữ từng từ; khi 'video này không thể lỗi' → glitch giả (lệch kênh màu, khung hình giật), sau đó 'Murphy's Law' và fade to black.",
    sfx: [
      { id: "swell", caption: 1, offset: 0 },
      { id: "ding", caption: 2, offset: 0.5, gainDb: -6 },
      { id: "glitch", caption: 4, offset: -0.2 },
      { id: "scratch", caption: 4, offset: 0.0, gainDb: -4 },
    ],
  },
];
