import type { SceneDef } from "./types.js";

export const TITLE_VI = "Nghịch lý Murphy: Vì sao mọi thứ luôn hỏng đúng lúc?";
export const TITLE_EN = "Murphy's Law: Why Things Always Go Wrong at the Worst Time";

export const SCENES: SceneDef[] = [
  {
    id: "scene-00",
    title: "Intro kênh",
    targetDuration: 16,
    music: "curious",
    summary: [0, 1, 3, 4],
    captions: [
      { vi: "Xin chào các bạn, chào mừng đến với Não Phẳng!", en: "Hi everyone, and welcome to Não Phẳng, the Flat Brain channel!" },
      { vi: "Nơi tụi mình hâm nóng lại những kiến thức nguội ngắt,", en: "The place where we reheat stone-cold facts," },
      { vi: "chẳng giúp bạn giàu thêm, cũng chẳng giúp bạn đẹp trai hơn,", en: "that won't make you richer, or better-looking," },
      { vi: "nhưng sẽ cứu bạn khi cuộc nhậu bắt đầu... im lặng.", en: "but will save you when the party goes... quiet." },
      { vi: "Hôm nay: vì sao vũ trụ luôn chọn đúng lúc bạn vội nhất để giở chứng?", en: "Today: why does the universe always act up exactly when you're in a hurry?" },
    ],
    visual_summary: "Logo kênh 'NÃO PHẲNG' nảy vào, bộ não bị ép phẳng; tagline gạch đầu dòng hài; thẻ chủ đề 'Nghịch lý Murphy'.",
    shots: [{ id: "s02-thinking", fromCaption: 0 }],
    animation:
      "Nền ảnh nhân vật mờ + tối; bộ não vector rơi xuống, bị ép bẹp (squash) khi đọc 'Não Phẳng' kèm logo; 3 thẻ: 'Giàu hơn ✗', 'Đẹp trai hơn ✗', 'Cứu cuộc nhậu ✓' pop-in theo câu; cuối intro thẻ chủ đề trượt vào.",
    sfx: [
      { id: "swell", caption: 0, offset: -0.6 },
      { id: "thud", caption: 0, offset: 1.6 },
      { id: "pop", caption: 1, offset: 0.4 },
      { id: "error", caption: 2, offset: 0.9, gainDb: -6 },
      { id: "error", caption: 2, offset: 2.4, gainDb: -6 },
      { id: "success", caption: 3, offset: 2.4 },
      { id: "whoosh", caption: 4, offset: 0.1 },
    ],
  },
  {
    id: "scene-01",
    title: "Hook",
    targetDuration: 24,
    music: "curious",
    summary: [0, 4, 6, 7],
    captions: [
      { vi: "Bảy giờ sáng. Bạn, một người trưởng thành có trách nhiệm, đang vội đi làm.", en: "7 a.m. You, a responsible adult, are rushing off to work." },
      { vi: "Lần này bạn đã chuẩn bị từ tối hôm trước, kỹ như sắp đi thi đại học.", en: "This time you prepped the night before, like it was a university entrance exam." },
      { vi: "Quần áo là phẳng lì. Điện thoại đầy pin. Báo thức đặt hẳn ba cái.", en: "Clothes ironed flat. Phone fully charged. Three alarms, just in case." },
      { vi: "Bạn bước ra khỏi nhà với thần thái của nhân vật chính...", en: "You step out the door with full main-character energy..." },
      { vi: "Và đúng lúc đó, trời đổ mưa. Xe thì đề mãi không nổ.", en: "And right then, it starts pouring. The scooter just won't start." },
      { vi: "Còn chìa khóa nhà... vừa bốc hơi khỏi vũ trụ.", en: "And your house keys... have evaporated from the universe." },
      { vi: "Bạn có bao giờ cảm thấy cuộc đời dường như cố tình chống lại kế hoạch của mình không?", en: "Have you ever felt like life is deliberately working against your plans?" },
      { vi: "Yên tâm, không phải nghiệp quật đâu. Chuyện này có hẳn một cái tên nửa khoa học: Nghịch lý Murphy.", en: "Relax, it's not bad karma. This has a half-scientific name: Murphy's Law." },
    ],
    visual_summary:
      "Buổi sáng tự tin trong căn hộ (đồng hồ, checklist) → bước ra ngoài, mưa đổ, xe không nổ, mặt sốc.",
    shots: [
      {
        id: "s01a-morning",
        fromCaption: 0,
        prompt: {
          scene: "the character confidently buttoning his shirt next to a neatly packed backpack, phone on a charger showing full battery, wall clock near 7 o'clock, smug satisfied smile",
          environment: "small cozy modern Vietnamese apartment, window with morning city view, a few plants",
          composition: "cinematic wide shot, character slightly left of center, empty space on the right",
          lighting: "soft golden morning light through the window",
          mood: "optimistic, organized, quietly proud",
          camera: "eye level, 35mm lens feel",
        },
      },
      {
        id: "s01b-rain-scooter",
        fromCaption: 4,
        prompt: {
          scene: "the character standing next to his scooter outside an apartment building, the scooter will not start, rain starting to fall, he pats his empty pockets looking for missing keys, exaggerated shocked expression, comedic body language",
          environment: "narrow urban Vietnamese street, apartment entrance, wet pavement, grey clouds",
          composition: "cinematic wide composition, character center-left, scooter beside him, sky area at the top",
          lighting: "cool overcast light with soft reflections on wet ground",
          mood: "comedic disaster, sudden bad luck",
          camera: "slightly low angle, wide lens",
        },
      },
    ],
    animation:
      "Camera đẩy chậm vào nhân vật (100%→108%, easeInOutCubic); đồng hồ vector chạy kim; checklist tick lần lượt; cắt sang shot mưa: hạt mưa xuất hiện, rung camera khi xe không nổ, dấu '!' bật easeOutBack; kết thúc tiêu đề 'Murphy's Law' hiện lên.",
    sfx: [
      { id: "tick", caption: 0, offset: 0.0 },
      { id: "ding", caption: 2, offset: 0.4 },
      { id: "ding", caption: 2, offset: 1.5 },
      { id: "ding", caption: 2, offset: 2.6 },
      { id: "whoosh", caption: 4, offset: -0.3 },
      { id: "rain", caption: 4, offset: 0 },
      { id: "crank", caption: 4, offset: 2.2 },
      { id: "scratch", caption: 5, offset: 0.9 },
      { id: "swell", caption: 7, offset: 2.0 },
    ],
  },
  {
    id: "scene-02",
    title: "Murphy's Law là gì?",
    targetDuration: 36,
    music: "curious",
    summary: [1, 4],
    captions: [
      { vi: "Nghịch lý Murphy gói gọn trong một câu nghe rất... bi quan:", en: "Murphy's Law fits into one very... pessimistic sentence:" },
      { vi: "“Điều gì có thể xảy ra sai, thì nó sẽ xảy ra sai.”", en: "“Anything that can go wrong, will go wrong.”" },
      { vi: "Tên gọi được cho là đến từ Edward Murphy, một kỹ sư hàng không Mỹ cuối thập niên 1940. Chắc hôm đó ông ấy xui lắm.", en: "The name is said to come from Edward Murphy, an American aerospace engineer in the late 1940s. He must have had a rough day." },
      { vi: "Nghe thì oách như định luật vật lý, nhưng thật ra không phải.", en: "It sounds as fancy as a law of physics, but it really isn't." },
      { vi: "Newton không chứng minh nó, và cũng chưa ai chứng minh được vũ trụ ghét bạn.", en: "Newton never proved it, and nobody has proven the universe hates you either." },
      { vi: "Nó chỉ là một cách nói vui về rủi ro, xác suất và sự chuẩn bị.", en: "It's just a playful way of talking about risk, probability, and preparation." },
      { vi: "Và về một tật rất người: chuyện xui thì nhớ dai, chuyện suôn sẻ thì quên sạch.", en: "And about a very human habit: bad luck sticks, smooth days vanish from memory." },
    ],
    visual_summary: "Nhân vật đứng giữa không gian tối giản, nhìn trái phải; câu trích dẫn hiện lên; icon thất bại xuất hiện lần lượt.",
    shots: [
      {
        id: "s02-thinking",
        fromCaption: 0,
        prompt: {
          scene: "the character standing with one hand on his chin, raising an eyebrow, glancing sideways with a skeptical, curious look",
          environment: "minimal abstract background of soft teal and warm paper tones with subtle geometric shapes",
          composition: "medium-wide shot, character in the lower right third, large clean negative space on the left and top for overlays",
          lighting: "soft studio key light with gentle rim light",
          mood: "curious, witty, slightly skeptical",
          camera: "eye level, gentle depth of field",
        },
      },
    ],
    animation:
      "Câu 'Anything that can go wrong...' gõ từng chữ ở vùng trống bên trái; icon thất bại (pin cạn, mưa, đèn đỏ, bug, chìa khóa) pop-in tuần tự easeOutBack; nhân vật 'nhìn trái/phải' bằng pan ngang nhẹ; dấu gạch chéo lên 'định luật vật lý'.",
    sfx: [
      { id: "whoosh", caption: 0, offset: -0.4 },
      { id: "typing", caption: 1, offset: 0 },
      { id: "pop", caption: 5, offset: 0.2 },
      { id: "pop", caption: 5, offset: 0.9 },
      { id: "pop", caption: 5, offset: 1.6 },
      { id: "pop", caption: 6, offset: 0.4 },
      { id: "pop", caption: 6, offset: 1.1 },
      { id: "error", caption: 3, offset: 2.2, gainDb: -6 },
    ],
  },
  {
    id: "scene-03",
    title: "Bánh mì phết bơ",
    targetDuration: 36,
    music: "curious",
    summary: [1, 4],
    shortable: true,
    captions: [
      { vi: "Ví dụ kinh điển số một: lát bánh mì phết bơ.", en: "Classic example number one: buttered toast." },
      { vi: "Bạn lỡ tay làm rơi. Và như có định mệnh, mặt bơ úp thẳng xuống sàn. Bẹp.", en: "You drop it. And as if by fate, it lands butter-side down. Splat." },
      { vi: "Bánh mì có thù với bạn à? Không hẳn.", en: "Does the toast hold a grudge? Not exactly." },
      { vi: "Bánh thường rơi từ độ cao mặt bàn, và bắt đầu xoay ngay khi trượt khỏi mép.", en: "Toast usually falls from table height, and starts spinning as soon as it slips off the edge." },
      { vi: "Ở độ cao đó, nó chỉ kịp lộn khoảng nửa vòng là tiếp đất. Vật lý thôi, không phải nghiệp.", en: "From that height, it only manages about half a flip before landing. Physics, not karma." },
      { vi: "Còn những lần rơi ngửa? Bạn nhặt lên ăn tiếp, rồi quên luôn là nó từng rơi.", en: "And when it lands butter-up? You pick it up, eat it, and forget it ever fell." },
    ],
    visual_summary: "Bếp nhỏ buổi sáng; lát bánh vector rơi, xoay nửa vòng, úp bơ xuống, nảy nhẹ; sơ đồ quỹ đạo + nhãn độ cao.",
    shots: [
      {
        id: "s03-kitchen",
        fromCaption: 0,
        prompt: {
          scene: "the character in a small kitchen staring down at the floor in disbelief, one hand frozen mid-air as if he just dropped something, mouth open, empty plate on the counter",
          environment: "compact bright Vietnamese apartment kitchen, wooden counter at waist height, tiled floor clearly visible in the lower part of the frame",
          composition: "wide shot, character on the left third, counter edge and an open stretch of floor on the right half kept clear",
          lighting: "warm morning light from a side window",
          mood: "comic disbelief",
          camera: "eye level, slightly wide",
        },
      },
    ],
    animation:
      "Lát bánh (vẽ bằng canvas) trượt khỏi mép bàn, xoay ~180° theo trọng lực, camera theo bánh xuống (tilt), va chạm có bounce + squash, vệt bơ; đường quỹ đạo nét đứt + nhãn '~75 cm' và '½ vòng'; icon não 'nhớ'/'quên'.",
    sfx: [
      { id: "whoosh", caption: 1, offset: 0.5 },
      { id: "thud", caption: 1, offset: 1.4 },
      { id: "scratch", caption: 2, offset: 0.1 },
      { id: "pop", caption: 3, offset: 0.6 },
      { id: "pop", caption: 4, offset: 0.6 },
      { id: "thud", caption: 4, offset: 2.4, gainDb: -6 },
    ],
  },
  {
    id: "scene-04",
    title: "USB",
    targetDuration: 34,
    music: "curious",
    summary: [1, 2, 3, 4, 5],
    shortable: true,
    captions: [
      { vi: "Bài kiểm tra nhân phẩm của thời đại công nghệ: cắm USB.", en: "The ultimate character test of the tech age: plugging in a USB." },
      { vi: "USB chỉ có hai mặt. Xác suất cắm đúng: năm mươi phần trăm. Dễ ợt.", en: "A USB plug has two sides. Odds of getting it right: fifty percent. Easy." },
      { vi: "Lần một. Sai.", en: "Try one. Wrong." },
      { vi: "Lật lại. Vẫn sai?!", en: "Flip it. Still wrong?!" },
      { vi: "Lật thêm lần nữa... và nó vào. Đúng y cái hướng ban đầu.", en: "Flip it once more... and it goes in. Exactly the way you had it at first." },
      { vi: "Toán học nói năm mươi phần trăm. Cuộc đời nói: còn lâu nhé.", en: "Math says fifty percent. Life says: nice try." },
    ],
    visual_summary: "Bàn làm việc, nhân vật cầm USB bực bội; cận cảnh vector: USB tiến vào cổng, bật ra, xoay 180°, bật ra, khựng lại, xoay, vào.",
    shots: [
      {
        id: "s04-desk-usb",
        fromCaption: 0,
        prompt: {
          scene: "the character sitting at a desk, leaning toward the side of a laptop, squinting with intense concentration while holding a small USB stick, comically frustrated eyebrows",
          environment: "tidy home office desk, laptop, desk lamp, small plant, calm wall",
          composition: "medium shot, character on the right half, the left half of the frame is a clean calm wall area",
          lighting: "warm desk lamp light mixed with cool daylight",
          mood: "focused frustration, everyday comedy",
          camera: "eye level, medium focal length",
        },
      },
    ],
    animation:
      "Panel cận cảnh bên trái: cổng USB + đầu USB vector. Lần 1 tiến vào → bật lại (shake, dấu X đỏ); xoay 180° (easeInOutCubic) → lần 2 bật lại; khựng 'dramatic pause' (zoom nhẹ, nhạc nín); xoay lại → cắm vào (easeOutBack, dấu ✓ xanh). Đồng hồ 50% hiện ở caption 2.",
    sfx: [
      { id: "whoosh", caption: 0, offset: -0.3 },
      { id: "error", caption: 2, offset: 0.9 },
      { id: "whoosh", caption: 3, offset: 0.1, gainDb: -6 },
      { id: "error", caption: 3, offset: 1.0 },
      { id: "whoosh", caption: 4, offset: 0.2, gainDb: -6 },
      { id: "success", caption: 4, offset: 2.0 },
      { id: "ding", caption: 5, offset: 0.2 },
    ],
  },
  {
    id: "scene-05",
    title: "Khi viết code",
    targetDuration: 48,
    music: "curious",
    summary: [0, 2, 3, 4, 7],
    shortable: true,
    captions: [
      { vi: "Còn nếu bạn là lập trình viên, chắc chắn bạn từng thốt lên câu thần chú: “Ở máy em chạy mà!”", en: "If you're a developer, you've definitely said the magic words: “But it works on my machine!”" },
      { vi: "Ở local, mọi thứ đẹp như mơ. Build xanh, test xanh, tâm hồn cũng xanh.", en: "Locally, it's a dream. Green build, green tests, green soul." },
      { vi: "Rồi bạn tự tin bấm deploy lên production... vào chiều thứ Sáu.", en: "Then you confidently deploy to production... on a Friday afternoon." },
      { vi: "Thiếu biến môi trường. API timeout.", en: "Missing environment variable. API timeout." },
      { vi: "Package lệch phiên bản. Database dỗi, không thèm kết nối.", en: "Package version mismatch. The database sulks and refuses to connect." },
      { vi: "Nhưng khoan, Murphy không nói code của bạn chắc chắn sẽ lỗi.", en: "But wait, Murphy isn't saying your code is doomed." },
      { vi: "Ông ấy chỉ nhắc: lỗi nào có thể xảy ra mà bạn không chuẩn bị,", en: "He's just reminding you: if a failure can happen and you haven't prepared for it," },
      { vi: "thì sớm muộn gì nó cũng xảy ra, và thường là đúng lúc sếp đang xem demo.", en: "sooner or later it will, usually right when your boss is watching the demo." },
    ],
    visual_summary: "Nhân vật tự tin trước laptop, terminal xanh 'works locally'; chuyển sang production: đèn đỏ, lỗi bật ra, icon .env biến mất, mặt sốc.",
    shots: [
      {
        id: "s05a-dev-confident",
        fromCaption: 0,
        prompt: {
          scene: "the character sitting at a laptop leaning back in his chair with arms crossed and a confident smug grin, coffee mug beside him",
          environment: "modern cozy workspace, soft green and teal accents, monitor glow, bookshelf softly blurred",
          composition: "medium-wide shot, character on the right third, left half of the frame kept as a calm dark wall for UI overlays",
          lighting: "soft cool screen glow plus warm ambient lamp",
          mood: "confident, everything under control",
          camera: "eye level, slight three-quarter angle",
        },
      },
      {
        id: "s05b-dev-shocked",
        fromCaption: 2,
        prompt: {
          scene: "the same character at the same laptop, now leaning forward in panic, hands on his head, eyes wide, mouth open, cold sweat drop",
          environment: "same workspace at night, red alert glow reflecting from the screen onto his face and the wall",
          composition: "medium-wide shot, character on the right third, left half of the frame kept as dark wall space for UI overlays",
          lighting: "dramatic red and cool blue glow from the screen, dark room",
          mood: "production incident panic, comedic",
          camera: "eye level, slight dutch tilt",
        },
      },
    ],
    animation:
      "Terminal UI gõ lệnh 'npm install', 'npm run build', 'npm test' với dòng xanh ✓ 'works locally'; chuyển cảnh glitch sang production; các thẻ lỗi đỏ pop-in (ENV missing, API timeout, version mismatch, DB connection failed) kèm rung; icon '.env' mờ dần biến mất; nhân vật từ tự tin sang hoảng (đổi shot + flash đỏ); cuối scene trích dẫn Murphy nổi lên.",
    sfx: [
      { id: "typing", caption: 1, offset: 0 },
      { id: "success", caption: 1, offset: 3.0 },
      { id: "whoosh", caption: 2, offset: 0.6 },
      { id: "error", caption: 3, offset: 0.1 },
      { id: "error", caption: 3, offset: 1.6 },
      { id: "error", caption: 4, offset: 0.1 },
      { id: "error", caption: 4, offset: 1.8 },
      { id: "swell", caption: 6, offset: 0 },
    ],
  },
  {
    id: "scene-06",
    title: "Trong đời sống",
    targetDuration: 38,
    music: "curious",
    summary: [1, 2, 5],
    shortable: true,
    captions: [
      { vi: "Và Murphy không chỉ ám dân IT. Ông ấy ám tất cả chúng ta.", en: "And Murphy doesn't just haunt IT folks. He haunts all of us." },
      { vi: "Đang muộn giờ? Đèn đỏ cả thành phố hẹn nhau chờ bạn.", en: "Running late? Every red light in town teams up to wait for you." },
      { vi: "Cần Internet gấp? Wi-Fi lập tức xin nghỉ phép.", en: "Urgently need the internet? The Wi-Fi instantly takes a day off." },
      { vi: "Mang ô theo? Trời nắng chang chang cả ngày.", en: "Bring an umbrella? Blazing sun all day." },
      { vi: "Để ô ở nhà? Mưa như chưa từng được mưa.", en: "Leave it at home? It rains like it's never rained before." },
      { vi: "Và khi cần gọi một cuộc điện thoại quan trọng... pin còn đúng một phần trăm. Một. Phần. Trăm.", en: "And when you need to make an important call... your battery is at exactly one percent. One. Percent." },
    ],
    visual_summary: "Montage nhanh: kẹt đèn đỏ trên xe máy; Wi-Fi biến mất; ô + nắng / không ô + mưa; điện thoại 1%.",
    shots: [
      {
        id: "s06a-traffic",
        fromCaption: 0,
        prompt: {
          scene: "the character on his scooter wearing a helmet, stopped at a red light, checking his wristwatch with an exasperated look, other scooters around him",
          environment: "busy Vietnamese city intersection in the morning, shop fronts, power lines",
          composition: "cinematic wide composition, character center-right, upper left area kept relatively open",
          lighting: "bright hazy morning sunlight",
          mood: "impatient, comedic frustration",
          camera: "eye level, wide lens",
        },
      },
      {
        id: "s06b-umbrella-sun",
        fromCaption: 3,
        prompt: {
          scene: "the character walking on a sunny sidewalk holding a closed umbrella, sweating slightly, looking up at a perfectly clear sky with an annoyed deadpan face",
          environment: "sunny Vietnamese street with trees and shophouses",
          composition: "wide shot, character center, lots of bright sky at the top",
          lighting: "strong bright midday sunlight, crisp soft shadows",
          mood: "ironic, deadpan humor",
          camera: "slightly low angle",
        },
      },
      {
        id: "s06c-phone-battery",
        fromCaption: 5,
        prompt: {
          scene: "the character holding his smartphone close to his face, staring at it in horror, the phone screen glowing red, sweat drop",
          environment: "simple blurred street background at dusk",
          composition: "medium close-up, character on the right half, left half of the frame calm and blurred",
          lighting: "dusk ambient light with red glow from the phone on his face",
          mood: "panic, comedic tension",
          camera: "eye level, shallow depth of field",
        },
      },
    ],
    animation:
      "Montage nhịp nhanh với wipe chuyển cảnh: đèn giao thông vector chuyển xanh→vàng→đỏ; icon Wi-Fi rút từng vạch rồi biến mất kèm dấu '!'; nắng: tia nắng xoay; cắt mưa: overlay mưa + tối trời; pin tụt 100%→1% nhấp nháy đỏ.",
    sfx: [
      { id: "whoosh", caption: 1, offset: -0.2 },
      { id: "click", caption: 1, offset: 1.2 },
      { id: "whoosh", caption: 2, offset: -0.2 },
      { id: "error", caption: 2, offset: 1.6 },
      { id: "whoosh", caption: 3, offset: -0.2 },
      { id: "rain", caption: 4, offset: 0.2 },
      { id: "whoosh", caption: 5, offset: -0.2 },
      { id: "error", caption: 5, offset: 2.6 },
    ],
  },
  {
    id: "scene-07",
    title: "Vì sao ta thấy Murphy đúng?",
    targetDuration: 48,
    music: "curious",
    summary: [2, 3, 5],
    captions: [
      { vi: "Vậy tại sao ta lại thấy Murphy linh nghiệm đến thế?", en: "So why does Murphy's Law feel so spot-on?" },
      { vi: "Lý do một: não của chúng ta là fan cứng của drama.", en: "Reason one: our brain is a die-hard drama fan." },
      { vi: "Lỡ một chuyến bay, kể cả chục năm. Trăm chuyến đúng giờ, chẳng ai thèm nhắc.", en: "Miss one flight and you'll tell the story for a decade. A hundred on-time flights, nobody mentions." },
      { vi: "Giới tâm lý học gọi đó là thiên kiến tiêu cực.", en: "Psychologists call this negativity bias." },
      { vi: "Lý do hai: đã tin mình xui, thì nhìn đâu cũng thấy bằng chứng mình xui.", en: "Reason two: once you believe you're unlucky, you see proof everywhere." },
      { vi: "Đó là thiên kiến xác nhận.", en: "That's confirmation bias." },
      { vi: "Lý do ba: chuyện gì càng dễ nhớ lại, ta càng tưởng nó xảy ra thường xuyên.", en: "Reason three: the easier something is to recall, the more often we think it happens." },
      { vi: "Ngày bình yên trôi qua như gió. Ngày xui thì dọn vào ở hẳn trong trí nhớ.", en: "Peaceful days blow right by. Unlucky days move into your memory for good." },
    ],
    visual_summary: "Nhân vật ngồi trầm tư; bong bóng ký ức nổi lên: chuyện xui phình to, rực màu; chuyện suôn sẻ nhỏ lại, mờ dần.",
    shots: [
      {
        id: "s07-memory",
        fromCaption: 0,
        prompt: {
          scene: "the character sitting on a park bench, looking up thoughtfully at the empty sky above him, chin resting on his hand, calm reflective expression",
          environment: "quiet city park at late afternoon, soft trees, open sky",
          composition: "wide shot, character small in the lower center, the entire upper two thirds of the frame is open soft sky for overlays",
          lighting: "soft warm late-afternoon light",
          mood: "reflective, gentle, curious",
          camera: "eye level, wide lens, deep negative space",
        },
      },
    ],
    animation:
      "Bong bóng ký ức nổi lên từ đầu nhân vật (bob nhẹ); bong bóng xui (mưa, đèn đỏ, USB, bug) phình to + màu đậm; bong bóng 'bình thường' (✓ đúng giờ, ☀) thu nhỏ, mờ, trôi về nền; nhãn 3 thiên kiến xuất hiện theo câu thoại.",
    sfx: [
      { id: "bubble", caption: 1, offset: 0.3 },
      { id: "bubble", caption: 2, offset: 0.2 },
      { id: "bubble", caption: 2, offset: 1.2 },
      { id: "ding", caption: 3, offset: 0.3 },
      { id: "ding", caption: 5, offset: 0.1 },
      { id: "bubble", caption: 6, offset: 0.3 },
      { id: "ding", caption: 6, offset: 0.2, gainDb: -6 },
    ],
  },
  {
    id: "scene-08",
    title: "Murphy có vô nghĩa?",
    targetDuration: 38,
    music: "warm",
    summary: [2, 4],
    captions: [
      { vi: "Vậy Nghịch lý Murphy chỉ để than thở thôi à? Không hề!", en: "So is Murphy's Law just for complaining? Not at all!" },
      { vi: "Dùng đúng cách, nó là một bí kíp quản lý rủi ro cực xịn.", en: "Used right, it's a top-tier risk-management cheat code." },
      { vi: "Sao lưu dữ liệu, vì ổ cứng có thể ra đi không một lời từ biệt.", en: "Back up your data, because hard drives can leave without saying goodbye." },
      { vi: "Chạy test trước khi deploy, vì code có thể phản bội bạn.", en: "Run tests before deploying, because code can betray you." },
      { vi: "Mang sạc dự phòng, ra sân bay sớm, và luôn giấu sẵn một phương án B.", en: "Carry a power bank, get to the airport early, and always keep a Plan B up your sleeve." },
      { vi: "Kỹ sư, phi công hay bác sĩ đều sống theo tinh thần này. Họ không bi quan, họ chỉ... có chuẩn bị.", en: "Engineers, pilots, and doctors live by this. They're not pessimists, just... prepared." },
    ],
    visual_summary: "Hỗn loạn biến thành checklist: icon backup, test, ô, sạc dự phòng, thẻ Plan B lần lượt được tick.",
    shots: [
      {
        id: "s08-prepared",
        fromCaption: 0,
        prompt: {
          scene: "the character calmly packing a backpack on a table: a power bank, a folded umbrella, a small external hard drive, a laptop, with a relaxed confident smile",
          environment: "bright tidy apartment by a window, morning",
          composition: "medium-wide shot, character and table on the right half, left half of the frame is a clean light wall for a checklist overlay",
          lighting: "fresh soft morning daylight",
          mood: "calm, prepared, quietly confident",
          camera: "eye level, gentle three-quarter angle",
        },
      },
    ],
    animation:
      "Icon lỗi hỗn loạn xoay tròn rồi 'hút' vào panel checklist; 5 dòng checklist (Backup, Test, Ô, Sạc dự phòng, Plan B) trượt vào + tick xanh easeOutBack theo câu thoại; thẻ Plan B lật ra.",
    sfx: [
      { id: "swell", caption: 0, offset: 1.5 },
      { id: "whoosh", caption: 1, offset: 0.4 },
      { id: "success", caption: 2, offset: 0.5 },
      { id: "success", caption: 3, offset: 0.5 },
      { id: "click", caption: 4, offset: 0.4 },
      { id: "click", caption: 4, offset: 1.6 },
      { id: "success", caption: 4, offset: 3.2 },
    ],
  },
  {
    id: "scene-09",
    title: "Kết luận",
    targetDuration: 28,
    music: "warm",
    summary: [1, 3, 4],
    captions: [
      { vi: "Tóm lại, Nghịch lý Murphy không có nghĩa là cuộc đời luôn chống lại bạn.", en: "So, Murphy's Law doesn't mean life is always against you." },
      { vi: "Nó có nghĩa là: nếu một điều có thể đi sai, hãy chuẩn bị cho nó.", en: "It means: if something can go wrong, prepare for it." },
      { vi: "Bình tĩnh, có kế hoạch, và có cả kế hoạch cho cái kế hoạch đó.", en: "Stay calm, make a plan, and make a plan for that plan." },
      { vi: "Và nếu bạn nghĩ video này không thể lỗi...", en: "And if you think this video can't possibly go wrong..." },
      { vi: "...hãy nhớ đến Murphy.", en: "...remember Murphy." },
    ],
    visual_summary: "Nhân vật mỉm cười trên ban công hoàng hôn với tách cà phê; câu kết hiện ra; glitch hài cuối rồi fade đen.",
    shots: [
      {
        id: "s09-calm",
        fromCaption: 0,
        prompt: {
          scene: "the character standing on a small balcony holding a cup of coffee, relaxed genuine smile, looking at the viewer",
          environment: "Vietnamese city rooftops at golden hour, potted plants on the balcony",
          composition: "medium-wide shot, character on the right third, open sky on the left for a quote",
          lighting: "warm golden-hour sunset light, soft long shadows",
          mood: "calm, warm, reassuring",
          camera: "eye level, gentle depth",
        },
      },
    ],
    animation:
      "Camera kéo ra chậm, bụi nắng lơ lửng; câu kết 'If it can go wrong, prepare for it' hiện chữ từng từ; khi 'video này không thể lỗi' → glitch giả (lệch kênh màu, khung hình giật), sau đó 'Murphy's Law' và fade to black.",
    sfx: [
      { id: "swell", caption: 1, offset: 0 },
      { id: "ding", caption: 2, offset: 0.5, gainDb: -6 },
      { id: "glitch", caption: 4, offset: -0.2 },
      { id: "scratch", caption: 4, offset: 0.0, gainDb: -4 },
    ],
  },
  {
    id: "scene-10",
    title: "Outro kênh",
    targetDuration: 20,
    music: "warm",
    summary: [3, 4],
    captions: [
      { vi: "Ơ... video vẫn chạy kìa. Chắc hôm nay Murphy đi nghỉ phép.", en: "Huh... the video's still running. Murphy must be on vacation today." },
      { vi: "Cảm ơn bạn đã xem đến tận đây. Nếu thấy vui, bấm like cho tụi mình nhé.", en: "Thanks for watching all the way to the end. If you had fun, hit like." },
      { vi: "Còn nếu thấy vô dụng... thì chuẩn rồi, đó là thương hiệu của kênh.", en: "And if it felt useless... that's right, that's our brand." },
      { vi: "Nhớ đăng ký kênh ngay, phòng khi lát nữa nút đăng ký... bị lỗi.", en: "Subscribe now, just in case the subscribe button... breaks later." },
      { vi: "Não Phẳng xin chào, hẹn gặp lại trong một kiến thức nguội ngắt khác. Bái bai!", en: "This was Não Phẳng. See you next time with more stone-cold facts. Bye-bye!" },
    ],
    visual_summary: "Sau màn đen, ảnh ban công hoàng hôn hiện lại; nút like, nhãn 'vô dụng = thương hiệu', nút đăng ký bị glitch; end card logo kênh.",
    shots: [{ id: "s09-calm", fromCaption: 0 }],
    animation:
      "Fade in từ đen, camera đẩy chậm; nút Like nảy + tim bay; nhãn 'Vô dụng ✓ (thương hiệu)'; nút ĐĂNG KÝ đỏ rung, glitch đúng chữ 'bị lỗi' rồi tự hồi phục; end card logo Não Phẳng + fade to black.",
    sfx: [
      { id: "scratch", caption: 0, offset: -0.3, gainDb: -6 },
      { id: "pop", caption: 1, offset: 2.4 },
      { id: "ding", caption: 2, offset: 2.0 },
      { id: "click", caption: 3, offset: 0.6 },
      { id: "glitch", caption: 3, offset: 2.9 },
      { id: "swell", caption: 4, offset: 0.2 },
    ],
  },
];
